apiVersion: v1
kind: Service
metadata:
  name: {{ include "hugo-app.fullname" . }}
  labels:
    {{- include "hugo-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: hugo
  selector:
    {{- include "hugo-app.selectorLabels" . | nindent 4 }}
